name: centinel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
        
      - name: do it!
        run: npm run do-it
      
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: centinels-list
          path: artifacts/index.html
